/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pfhcidjfkjrnfujekyit"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmaGNpZGpma2pybmZ1amVreWl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4NTI3NTUsImV4cCI6MjA3NzQyODc1NX0.uI87hDVpMamE3T4NfwXZC9DxwJIBX-jQ33u0M-to6nA"